version: '2'
services:
  mongo:
    image: mongo:3.4
    container_name: reskongoal-db
    volumes:
      - "data_mongo:/data/db"
    ports:
      - "27017:27017"
    command: --smallfiles --rest

  api:
    build:
      context: .
    command: yarn run dev
    volumes:
      - .:/reskongoal/api
    ports:
      - "8080:8080"
    links:
      - mongo
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGODB_URI=mongodb://mongo:27017/reskongoal

volumes:
  data_mongo:
